### ISSUE TITLE
Import/export functionality from a participatory process to another instance

### ISSUE THREAD

**Issue by armandfardeau** [OpenSourcePolitics/dev#7]
# Simple description feature
Import/export functionality from a participatory process and its associated data to another instance.

# Context
## User context

- As an admin, it is quite tedious to fill in the forms to create a participatory process especially when I'm working on a blank instance. 

## Feature proposal

- As an admin, I want to be able to export a participatory process and its associated data.
- As an admin when creating a new participatory process I want to be able to import a file containing all the info of a participatory process to no start from scratch.

# Mockups
![Button](https://user-images.githubusercontent.com/20232956/65618409-85052d00-dfbe-11e9-8d3d-43eaf22b0ad7.png)
_Here we can see the import and copy button, one located to the right of the process creation button, the other located in the action buttons of the participatory process_

Choose file from desktop
![import-modal](https://user-images.githubusercontent.com/20232956/65618454-964e3980-dfbe-11e9-9169-ffdd9e85c646.png)
_At import, a message indicates if the content can be created and if everything is ok, it creates the process with the default unpublished status._

# Constraints
- data which must be included in the participatory process export:
  - Info	
  - Steps	
  - Categories	
  - Components and settings
  - Files and folders
- data which must be included in the participatory process export:
All element requiring a user to be created, example on a proposal component, do not copy proposals since an associated user is needed.
Precisions, everything related to configuration
- for example survey questions will be exported

- the export file should be a JSON file
- Development should be made on branch 0.18-stable on our fork and on decidim/decidim master branch.

### Decision log
- Core --> https://meta.decidim.org/processes/roadmap/f/122/proposals/14760
- Decidim's repo 0.18-stable first, then master

**Comment by virgile-dev** [comment]
## Questions by Oliver 
_How do we manage images? can we simply copy their url?_
**Reply OSP :** use urls
_What happens if the exported file has 2 locales and the import is done in an organization with 5 locales? We leave locales in blank?_
**Reply OSP :** leave them blank
_What happens if the exported file has 5 locales and the import is done in an organization with 2 locales? Do we ignore not matching locales?_
**Reply OSP :** ignore
_What happens if the exported file has :en locale and the import is done in an organization with only :fr locale?_
**Reply OSP :** abort with a flash error
_On import we  plan to show a form asking for the title and the slug (which should be unique). Are you ok with this solution?_
**Reply OSP :** agree

**Comment by isaacmg410** [comment]
@virgile-dev @armandfardeau 
More doubts that we have.

If the exported file contains the information of a Scope, Area or ProcessGroup, and when user import this file to another platform that does not exist these information, what do we have to do?

- Ignore it?
- Create the related information? If this is the case, the exported file, must have all the information no? Parents, Children, type...?

**Comment by virgile-dev** [comment]
@isaacmg410 
- Scope and areas are organization related. I'd ignore them for import.
- Categories and subcategories are process and assembly related so I'd import them and should contain all the info to create them in the new participatory space
